http:
  host: [0, 0, 0, 0]
  port: 8080

mysql:
  host: ""
  port: 0
  user: ""
  password: ""
  database: ""
  require_ssl: true

argon2:
  secret: ""
  memory_size: 4096
  iterations: 3
  parallelism_factor: 1
  output_length: 32
