http:
  host: [127, 0, 0, 1]
  port: 8080

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  database: mysql
  require_ssl: false

argon2:
  secret: ""
  memory_size: 16
  iterations: 1
  parallelism_factor: 1
  output_length: 32
