name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: "password"
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:password@127.0.0.1:5432/postgres
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.72.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo install sqlx-cli
      - run: sqlx migrate run
      - run: cargo sqlx prepare --check -- --lib

  test:
    needs: check
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: "password"
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:password@127.0.0.1:5432/postgres
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.72.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo test

  clippy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.72.0
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy -- -D warnings

  fmt:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.72.0
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all --check
